# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

inhibit_all_warnings!
platform :ios, '8.0'
#use_frameworks!

target 'Demo' do
    #
    pod 'AFNetworking', ' 3.1.0'
    #
    pod 'MJRefresh', ' 3.1.10'
    #
    pod 'SDWebImage', ' 3.8.1'
    #
    pod 'Reachability', ' 3.2'
    #
    pod 'Masonry', ' 1.0.1'
    #
    pod 'SDCycleScrollView', ' 1.65'
    #
    pod 'FMDB', ' 2.6.2'
    #
    pod 'JSONModel', ' 1.2.0'
    #
    pod 'IQKeyboardManager', ' 6.0.3'
    #
    #pod 'MWPhotoBrowser', ' 2.1.2'
    #
    pod 'MBProgressHUD', '~> 1.1.0'
    #
    pod 'TZImagePickerController'
    #
    pod 'GPUImage'
    #
    pod 'DACircularProgress', ' 2.3.1'
    #
    pod 'YYCategories'
    #
    pod 'OOMDetector', '1.3'
    #
    pod 'fishhook', '0.2'
    #
    pod 'pop'
    #
    pod 'YYCache'
    #
    pod 'RTRootNavigationController', '0.6.7'
    #pod 'XMPPFramework', '4.0.0'
end
